# shfmt configuration
# https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.md

# Indent with 2 spaces
-i 2

# Switch case indent (one space)
-ci

# Binary operators at start of line
-bn

# Keep column alignment
-ka

# Operate on the files in place
-l
