#!/usr/bin/env bash
# scripts/lint.sh — Run shellcheck, shfmt, and structural checks.
#
# Usage: ./scripts/lint.sh [shellcheck|shfmt|format|clean|doctor]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

CLR_RED='\033[0;31m'
CLR_GREEN='\033[0;32m'
CLR_YELLOW='\033[1;33m'
CLR_BLUE='\033[0;34m'
CLR_RESET='\033[0m'

info()    { echo -e "${CLR_BLUE}ℹ️  $*${CLR_RESET}"; }
success() { echo -e "${CLR_GREEN}✅ $*${CLR_RESET}"; }
warn()    { echo -e "${CLR_YELLOW}⚠️  $*${CLR_RESET}" >&2; }
error()   { echo -e "${CLR_RED}❌ $*${CLR_RESET}" >&2; }

# Collect target files. Exclude:
#   - .git
#   - instances/, backups/  (runtime)
#   - .bats/  (test helpers generated by bats)
sh_targets() {
  find "${ROOT_DIR}" \
    \( -path "${ROOT_DIR}/.git" -o \
       -path "${ROOT_DIR}/instances" -o \
       -path "${ROOT_DIR}/backups" -o \
       -path "${ROOT_DIR}/.bats" \) -prune -o \
    -type f \( -name "*.sh" -o -name "*.bash" \) -print 2>/dev/null | sort
}

require_tool() {
  if ! command -v "$1" &>/dev/null; then
    error "Requerido pero no encontrado: $1"
    return 1
  fi
}

run_shellcheck() {
  require_tool shellcheck
  info "shellcheck..."
  local rc=0
  local f
  while IFS= read -r f; do
    if ! shellcheck "$f"; then
      rc=1
    fi
  done < <(sh_targets)
  if [[ "$rc" -eq 0 ]]; then
    success "shellcheck: clean"
  else
    error "shellcheck: hay issues que corregir"
  fi
  return "$rc"
}

run_shfmt_check() {
  require_tool shfmt
  info "shfmt check..."
  local files
  files=$(sh_targets)
  if [[ -z "$files" ]]; then
    success "shfmt: nothing to check"
    return 0
  fi
  # shellcheck disable=SC2086
  if shfmt -d -i 2 -ci -bn $files; then
    success "shfmt: clean"
  else
    error "shfmt: drift detectado (ejecuta 'make format')"
    return 1
  fi
}

run_shfmt_format() {
  require_tool shfmt
  info "shfmt format..."
  local files
  files=$(sh_targets)
  if [[ -n "$files" ]]; then
    # shellcheck disable=SC2086
    shfmt -w -i 2 -ci -bn $files
  fi
  success "shfmt: archivos formateados"
}

run_clean() {
  info "Limpiando artefactos..."
  rm -rf "${ROOT_DIR}/.bats"
  find "${ROOT_DIR}" -type f -name "*.bak" -delete 2>/dev/null || true
  find "${ROOT_DIR}" -type f -name "*.tmp" -delete 2>/dev/null || true
  success "Limpieza completada"
}

run_doctor() {
  local ok=0
  info "Verificando estructura del proyecto..."

  local required=(
    "openclaw-cluster.sh"
    "Dockerfile.openclaw-chrome"
    "docker-compose.template.yml"
    ".env.example"
    "README.md"
    "LICENSE"
    "Makefile"
    "VERSION"
    "CHANGELOG.md"
    "CONTRIBUTING.md"
    "CODE_OF_CONDUCT.md"
    "SECURITY.md"
    "scripts/lint.sh"
    "scripts/test-unit.sh"
    ".github/workflows/ci.yml"
  )

  local f
  for f in "${required[@]}"; do
    if [[ ! -e "${ROOT_DIR}/$f" ]]; then
      error "Falta: $f"
      ok=1
    fi
  done

  # Every .sh file must have shebang + set -euo pipefail (best-effort)
  while IFS= read -r f; do
    if ! head -n1 "$f" | grep -qE '^#!.*(ba)?sh'; then
      warn "Sin shebang: $f"
    fi
  done < <(sh_targets)

  if [[ "$ok" -eq 0 ]]; then
    success "Estructura OK"
  else
    error "Faltan archivos requeridos"
  fi
  return "$ok"
}

main() {
  local cmd="${1:-all}"
  case "$cmd" in
    all)        run_shellcheck && run_shfmt_check ;;
    shellcheck) run_shellcheck ;;
    shfmt)      run_shfmt_check ;;
    format)     run_shfmt_format ;;
    clean)      run_clean ;;
    doctor)     run_doctor ;;
    *)
      echo "Uso: $0 [shellcheck|shfmt|format|clean|doctor|all]" >&2
      exit 2
      ;;
  esac
}

main "$@"
